### ISSUE TITLE
Unexpected exception on Windows Server 2007

### ISSUE THREAD

**Issue by interdrift** [nreco/nreco#1]
I've been using nreco pdf generator, but I get an unexpected exception on windows server 2007,  it works fine on my windows 8 dev machine. What is the reason for this?
Also, how does it behave on windows xp?

**Comment by interdrift** [comment]
Also, how does it behave on windows xp?

**Comment by VitaliyMF** [comment]
Hi,

 but I get an unexpected exception on windows server 2007, it works fine on
> my windows 8 dev machine. What is the reason for this?


most typical reason of that is missed VC+ 2013 runtime libraries required
by wkhtmltopdf.

Also, how does it behave on windows xp?


PDF generator embeds latest release of wkhtmltopdf 0.12.2.1 compiled with
VC++ 2013 (it will not work on legacy versions of windows). You may install
MinGW build of wkhtmltopdf ( http://wkhtmltopdf.org/downloads.html ) and
use it instead of embedded wkhtmltopdf.exe image.


On Tue, Jun 9, 2015 at 10:26 AM, Hristo Hristov <notifications@github.com>
wrote:

> I've been using nreco pdf generator, but I get an unexpected exception on
> windows server 2007, it works fine on my windows 8 dev machine. What is the
> reason for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nreco/nreco/issues/1>.
>



-- 
_____________
NReco Support
http://www.nrecosite.com

**Comment by interdrift** [comment]
:+1: Thanks
